const defaultSettings = {
    "clock": true,
    "clockSeconds": false,
    "weather": true,
    "quote": true,
    "pet": true,
    "petType": "cat",
    "petSize": 64,
    "petFreq": 50,
    "customCity": "",
    "useCustomCity": false,
    "tempUnit": "celsius",
    "bookmarks": true,
    "bookmarkFolder": "Bookmarks Bar",
    "expandBookmarks": false,
    "topRight": true,
    "topRightOrder": [
        { "id": "chatgpt", "displayBool": true, "url": "https://chatgpt.com/" },
        { "id": "gemini", "displayBool": true, "url": "https://gemini.google.com/" },
        { "id": "claude", "displayBool": true, "url": "https://claude.ai/" },
        { "id": "perplexity", "displayBool": true, "url": "https://www.perplexity.ai/" },
        { "id": "copilot", "displayBool": true, "url": "https://copilot.microsoft.com/" }
    ],
    "pixelArt": true,
    "selectedPixelArt": "flowers",
    "customSVG": "",
    "pixelArtOpacity": 40,
    "pixelArtDensity": 20,
    "pixelArtColorDark": "#cccccc",
    "pixelArtColorLight": "#b04288",
    "availableWidgets": ["calendar", "todo", "pomodoro", "notes"],
    "useUnsplash": false,
    "unsplashApiKey": "",
    "unsplashUpdateFrequency": "daily",
    "showUnsplashRefresh": false,
    "backgroundImage": "",
    "bgAnimation": true,
    "bgAnimationType": "particles",
    "bgAnimationSpeed": 50,
    "bgAnimationDensity": 50,
    "sidebar": false,
    "sidebarPosition": "right",
    "sidebarWidgets": [],
    "sidebarExpanded": false,
    "sidebarShowCustomize": true,
    "autoHide": false,
    "customCSS": ""
}